### ISSUE TITLE
Naming them would not hurt :-)

### ISSUE THREAD

**Issue by PexMor** [LaskaKit/ESPink-42#5]
https://github.com/LaskaKit/ESPink-42/blob/da1134c9fca5b908fcb62d94b190ed9c36872ec6/SW/README.md?plain=1#L37

The libs that should be installed are:

- [FT6236G](https://github.com/bitbank2/FT6236G) (with dep: [BitBang_I2C(https://github.com/bitbank2/BitBang_I2C))
- [GxEPD2](https://github.com/ZinggJM/GxEPD2) (with deps: [Adafruit GFX Library](https://github.com/adafruit/Adafruit-GFX-Library) which depends on [Adafruit BusIO](https://github.com/adafruit/Adafruit_BusIO))

For information on libraries and their sources: <https://www.arduinolibraries.info>

It would be nice to add this info into the `README*.md`

**Comment by Konstantin-G** [comment]
File for FT6236 is in the folder SW/Simple/Touch_and_light_example/
[GxEPD2](https://github.com/ZinggJM/GxEPD2) was added
